[TASK] Update Response Handling to PSR-7
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #370
Opened 2020-11-08 14:30 UTC by susannemoog

See Core Breaking 92502
See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1082
Releases: 11.0

2020-11-09 08:57 UTC, mbrodala requested changes

2020-11-09 08:57 UTC, mbrodala commented on Documentation/10-Outlook/6-dispatching.rst
> +Thanks to this configuration, one can register custom :php:`RequestHandler`.
```suggestion
Thanks to this configuration, one can register a custom :php:`RequestHandler`.
```

2020-11-09 08:57 UTC, mbrodala commented on Documentation/10-Outlook/6-dispatching.rst
> +   Extbase does not use PSR-7 implementation for Requests, but
```suggestion
   Extbase does not use PSR-7 for requests, but
```

2020-11-09 08:57 UTC, mbrodala commented on Documentation/10-Outlook/6-dispatching.rst
> +The object :php:`Request` and is passed to the the Controller,
```suggestion
The object :php:`Request` is passed to the the Controller,
```

2020-11-09 08:57 UTC, mbrodala commented on Documentation/10-Outlook/6-dispatching.rst
> +   class HtmlResponse extends Response
Does it make sense to create a custom `HtmlResponse`? One could use the TYPO3 implementation or, since this is now the recommended way, use a response factory.

2020-11-09 08:57 UTC, mbrodala commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +:php:`Request` Object to the appropriate Controller.
```suggestion
:php:`Request` object to the appropriate controller.
```

2020-11-09 10:13 UTC, susannemoog commented on Documentation/10-Outlook/6-dispatching.rst
> +   class HtmlResponse extends Response
the TYPO3 implementation is marked as internal, ResponseFactory however would be a good point.

2020-11-13 12:32 UTC, susannemoog commented on Documentation/10-Outlook/6-dispatching.rst
> +   class HtmlResponse extends Response
Fixed.

2020-11-13 13:03 UTC, mbrodala commented on Documentation/10-Outlook/6-dispatching.rst
> +   class HtmlResponse extends Response
Awesome, thanks a lot!

2020-11-13 13:11 UTC, mbrodala approved these changes

2020-11-13 13:11 UTC, merged