[WIP][TASK] Extbase controller actions must return ResponseInterface
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #374
Opened 2020-11-30 17:12 UTC by brotkrueml

See: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/master/Deprecation-92784-ExtbaseControllerActionsMustReturnResponseInterface.html

Missing: How to handle redirect() and forward() calls inside actions?

2020-11-30 17:27 UTC, susannemoog commented
I did some changes for this change already: be careful with the examples code as that is taken directly Form the blog exanple extension and verified to be working. Especially: the actions of a controller extending the action controller may still return a string as that is converted to a proper response object by the parent as far as I understood.

2020-12-12 11:14 UTC, susannemoog commented
> I did some changes for this change already: be careful with the examples code as that is taken directly Form the blog exanple extension and verified to be working. Especially: the actions of a controller extending the action controller may still return a string as that is converted to a proper response object by the parent as far as I understood.

To clarify: that is deprecated, but we should adjust the blog example extension first and then update the docs here, otherwise we get a mismatch between the two.

2020-12-12 14:04 UTC, brotkrueml commented
> To clarify: that is deprecated, but we should adjust the blog example extension first and then update the docs here, otherwise we get a mismatch between the two.

I agree, will have a look at the extension.

2020-12-24 10:32 UTC, alexanderschnitzler requested changes
Most importantly, please revert the whitespace changes and all other changes that do not deal with this explicit change in Extbase. Think of it this way: You encounter a change in Extbase, read the docs, lookup the commits and then see a diff with dozens of changes instead of just the necessary change. That's quite distracting.

2020-12-24 10:32 UTC, alexanderschnitzler commented on Documentation/3-BlogExample/4-and-action.rst
> +         return $this->responseFactory->createHtmlResponse($this->view->render());
There is helper method `htmlResponse()` to ease the migration. We should use that in the blog example but explain this method and using the responseFactory while mentioning PSR-17.

2020-12-24 10:32 UTC, alexanderschnitzler commented on Documentation/3-BlogExample/4-and-action.rst
> +to recognize it as an action and returns an implementation of the
With this change the sentence is grammatically incorrect.

2020-12-24 10:32 UTC, alexanderschnitzler commented on Documentation/3-BlogExample/8-Back-in-the-controller.rst
> +      public function initializeAction()
Can we please just change one thing at a time, whitespaces or logic stuff? It makes the diff much easier.

2020-12-24 10:32 UTC, alexanderschnitzler commented on Documentation/3-BlogExample/8-Back-in-the-controller.rst
> +Action methods return a response object of type `\Psr\Http\Message\ResponseInterface`.
Please a the word `must` here.

2020-12-30 16:45 UTC, brotkrueml commented
@alexanderschnitzler Will take care of your suggestions. Before further processing of this issue I started to cleanup the blog_example code and then want to begin with adapting for v11. But the first PRs are not merged yet.

2021-01-24 10:52 UTC, linawolf commented
What is the status of this PR, @brotkrueml ?

2021-01-24 10:53 UTC, linawolf commented
sorry, accidently hit the wrong button...

2021-01-25 09:15 UTC, brotkrueml commented
@linawolf I started pull requests on the blog_example extension, but there was no feedback since. The goal is to make the blog_example extension clean, then make it v11 ready. After that adopt the code examples to the documentation.

2021-02-17 18:14 UTC, linawolf commented
So the question would be how to succeed.. Is there anyone who we could ping?

2021-02-20 11:03 UTC, susannemoog commented
@brotkrueml / @linawolf I checked the open PRs on the blog_example and merged them, so work can continue. Additionally, I gave you - Lina - write access to the blog example repository.

2021-05-01 07:57 UTC, linawolf commented
So @brotkrueml is it possible to merge this now or do you need further changes?

2021-05-05 16:06 UTC, brotkrueml commented
Hmm, don't know. The blog_example extension should be in line with the examples in this docs, as mentioned in a comment above. As this should be no problem, the tags doesn't work for me (in 10.4). Wanted to investigate that, but had other priorities. 

I was enthusiastic when the change was merged into the v11 core. Then started to dig into the blog example extension, adjusted some minor issues also for 10.4 before making the adjustments for v11. But the merges lasts some weeks and so my priorities shifted.

From my side, it can be merged and later make more adjustments. Someone can also take over the PR or it can be closed and make a fresh start.

2021-05-13 06:00 UTC, linawolf approved these changes

2021-05-13 06:11 UTC, linawolf approved these changes

2021-05-13 06:11 UTC, merged