Update 5-modeling-the-class-hierarchy.rst
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #388
Opened 2021-01-22 13:26 UTC by jankornblum

Updated code example for Extbase class / table mapping rrelated to #87623 (Replace config.persistence.classes typoscript configuration).

2021-01-22 14:36 UTC, mbrodala requested changes

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +data of the instances are stored and with which type they should be stored. This is done in "Configuration/Extbase/Persistence/Classes.php".
```suggestion
data of the instances are stored and with which type they should be stored. This is done in :file:`Configuration/Extbase/Persistence/Classes.php`.
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +                '\MyVendor\MyExtension\Domain\Model\ScientificInstitution' => MyVendor\MyExtension\Domain\Model\ScientificInstitution::class
```suggestion
                '\MyVendor\MyExtension\Domain\Model\ScientificInstitution' => MyVendor\MyExtension\Domain\Model\ScientificInstitution::class,
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'recordType' => '\MyVendor\MyExtension\Domain\Model\Person'
```suggestion
            'recordType' => '\MyVendor\MyExtension\Domain\Model\Person',
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'recordType' => '\MyVendor\MyExtension\Domain\Model\Company'
```suggestion
            'recordType' => '\MyVendor\MyExtension\Domain\Model\Company',
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'recordType' => '\MyVendor\MyExtension\Domain\Model\ScientificInstitution'
```suggestion
            'recordType' => '\MyVendor\MyExtension\Domain\Model\ScientificInstitution',
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +        ]
```suggestion
        ],
```

2021-01-22 14:36 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'tableName' => 'tx_myextension_domain_model_party',
There are mentions of this afterwards, can you also adjust them?

2021-01-22 14:50 UTC, jankornblum commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'tableName' => 'tx_myextension_domain_model_party',
Sorry. Very first time here. What do you mean in detail?

2021-01-22 14:52 UTC, mbrodala commented on Documentation/6-Persistence/5-modeling-the-class-hierarchy.rst
> +            'tableName' => 'tx_myextension_domain_model_party',
I mean this, which refers to the old TypoScript configuration:

![image](https://user-images.githubusercontent.com/5037116/105505984-d8c67a00-5cc9-11eb-93c7-4dcbaf219691.png)

2021-01-24 10:51 UTC, linawolf commented
What is the status of this PR, @mbrodala? Have all required changes been included?

2021-01-25 08:04 UTC, mbrodala approved these changes

2021-01-25 08:05 UTC, merged

2021-01-25 08:05 UTC, mbrodala commented
@linawolf Yes, all done.