Document missing TypeInterface feature
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #396
Opened 2021-02-16 09:37 UTC by DanielSiepmann

Add small explanation and example.
That way it should be possible to make use of this feature in custom
extensions.

Relates: #393

2021-02-16 09:38 UTC, DanielSiepmann commented
Valid since many versions, including 8.7, 9.5, 10.4.

2021-02-16 09:46 UTC, mbrodala requested changes

2021-02-16 09:46 UTC, mbrodala commented on Documentation/b-ExtbaseReference/Index.rst
> +               $this->serialized = $serialized;
We should unserialize the string here (preferrably using `json_decode()`) and use `array` as private value.

2021-02-16 09:46 UTC, mbrodala commented on Documentation/b-ExtbaseReference/Index.rst
> +               return $this->serialized;
Here we then need to serialize again of course.

2021-02-16 09:46 UTC, mbrodala commented on Documentation/b-ExtbaseReference/Index.rst
> +           // Add proper getter, e.g. for template …
We should add a more descriptive example here.

2021-02-23 21:15 UTC, linawolf commented
@mbrodala @DanielSiepmann  What is the status of this PR? Can you resolve the open comments?

2021-04-19 08:45 UTC, linawolf commented
@mbrodala @DanielSiepmann please get this PR resolved or closed.

2021-05-13 05:44 UTC, linawolf commented
@DanielSiepmann , @mbrodala I put this in draft. Please decide how to go on with this PR

2021-05-14 06:39 UTC, mbrodala approved these changes

2021-05-14 06:39 UTC, merged

2021-05-14 06:39 UTC, mbrodala commented
I've integrated JSON encode/decode now for a more real-world example.