composer.json
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #405
Opened 2021-03-06 21:27 UTC by franzholz

2021-03-08 08:43 UTC, mbrodala requested changes

2021-03-08 08:43 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +            "typo3/cms-core": "^9.5"
```suggestion
            "typo3/cms-core": "^10.4"
```

Since there will always people who blindly copy code we should at least suggest the current latest version.

2021-03-08 08:43 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +           "typo3-ter/store-inventory": "self.version"
Since composer.typo3.org is deprecated we should not suggest `typo3-ter/*` anymore.

2021-03-08 08:43 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +The :file:`composer.json` allows loading the extension with *composer* (PHP package manager).
```suggestion
The :file:`composer.json` allows loading the extension with Composer (PHP package manager).
```

2021-03-08 08:43 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +be activated in the extension manager. But at first the domain must be set up.
```suggestion
be activated in the extension manager. But first the domain must be set up.
```

2021-03-08 17:02 UTC, franzholz reviewed
I have removed the TYPO3 Core Team as authors here.

2021-03-09 07:53 UTC, mbrodala requested changes

2021-03-09 07:53 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +       }
```suggestion
        },
        "replace": {
            "myvendor/store-inventory": "self.version"
        }
```

2021-03-09 07:54 UTC, mbrodala approved these changes

2021-03-09 07:54 UTC, merged