Remove the remark tag with a Link
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #434
Opened 2021-05-04 02:59 UTC by andwee

I assume here is a missing  link to wikipedia instead of the <remark> Tags?

2021-05-04 06:11 UTC, mbrodala requested changes

2021-05-04 06:11 UTC, mbrodala commented on Documentation/8-Fluid/1-basic-concepts.rst
>      The Uniform Access Principle says all services offered by a
```suggestion
    The  `Uniform Access Principle <https://en.wikipedia.org/wiki/Uniform_access_principle>`__ says all services offered by a
```

2021-05-04 06:11 UTC, mbrodala commented on Documentation/8-Fluid/1-basic-concepts.rst
> +    computation. `Explanation on Wiki <https://en.wikipedia.org/wiki/Uniform_access_principle>`__
```suggestion
    computation.
```

2021-05-07 19:45 UTC, linawolf approved these changes

2021-05-07 19:45 UTC, merged