make registrating the same level as configuring
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #442
Opened 2021-05-10 21:30 UTC by franzholz

2021-05-11 05:10 UTC, linawolf requested changes

2021-05-11 05:10 UTC, linawolf commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +The plugin must be registered to have it appear as a selectable element in the backend. And the frontend must get the information which controller class to call for this plugin.
I don't get this sentence. The frontend must get the information how?

2021-05-12 05:32 UTC, linawolf requested changes

2021-05-12 05:32 UTC, linawolf commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +   defined('TYPO3_MODE') or die();
TYPO3_MODE got removed in LTS 11, defined('TYPO3') or die(); is correct

2021-05-12 05:32 UTC, linawolf commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +*  The first parameter denotes the extension name in UpperCamelCase (StoreInventory). Instead of this also the extension key in lower case with underscores can be given (store_inventory).
Lines should have a maximum length of 80 to fascílitate handling on Github etc. Please use linebreaks here

2021-05-12 05:32 UTC, linawolf commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +The plugin must be registered to have it appear as a selectable element in the backend. The **plugin name** must be the same as it has been used in the plugin configuration.
line to long

2021-05-12 05:32 UTC, linawolf commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +This example was intentionally simple.
let's not talk about "simple", this causes frustration. How about "basic"?

2021-05-12 05:47 UTC, franzholz commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +   defined('TYPO3_MODE') or die();
TYPO3_MODE is deprecated in TYPO3 11 and will be removed in TYPO3 12.
``

2021-05-12 05:56 UTC, franzholz commented on Documentation/4-FirstExtension/7-configuring-the-plugin.rst
> +This example was intentionally simple.
small glimpse

2021-05-12 06:02 UTC, linawolf approved these changes

2021-05-12 06:02 UTC, merged