explain more things
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #447
Opened 2021-05-14 12:20 UTC by franzholz

2021-05-14 12:33 UTC, mbrodala requested changes
Notice in general that Fluid does not have "methods", only viewhelpers.

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +* `<f:for each="{paginator.paginatedItems}" as="blog">[...]</f:for>` :
```suggestion
* `<f:for each="{paginator.paginatedItems}" as="blog">[…]</f:for>` :
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +* `<f:link.action action="index" controller="Post" arguments="{blog : blog}">{blog.title} ({f:translate(key: 'blog.numberOfPosts', arguments: '{numberOfPosts: \'{blog.posts -> f:count()}\'}')})</f:li
```suggestion
* `<f:link.action action="index" controller="Post" arguments="{blog : blog}">[…]</f:link.action>` :
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   creates a link to the `indexAction` method of the `PostController` which is `public function indexAction(Blog $blog, $tag = null)`.
```suggestion
   creates a link to the :php:`indexAction` method of the :php:`PostController` which is :php:`public function indexAction(Blog $blog, $tag = null)`. 
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   :file:`Resources/Private/Language/locallang.xml` refers to the text `%d posts`.
```suggestion
   The blog stored in the variable `{blog}` is passed as `blog` parameter to the action.

* `{f:translate(key: 'blog.numberOfPosts', arguments: '{numberOfPosts: \'{blog.posts -> f:count()}\'}')}`
   The translation key `blog.numberOfPosts` refers to the translation file:`Resources/Private/Language/locallang.xml`.
   The number of `{blog.posts}` is counted using the `f:count()` viewhelper and passed as argument to the `f:translate()` viewhelper. This viewhelper inserts the argument into the translation text `%d posts`. 
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   The fluid method `f:translate(...)` fetches this string and replaces its `%d` argument by the number of posts for the current blog.
```suggestion
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   `{blog.posts}` is the array of posts which belong to the current blog. The class `Blog` contains the protected variable `$posts`.
```suggestion
   `{blog.posts}` is the list of posts which belong to the current blog. The class `Blog` contains a getter method `getPosts()` which is automatically used to access the list of posts (:php:`\TYPO3\CMS\Extbase\Persistence\ObjectStorage`).
```

2021-05-14 12:33 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   This is the member variable (of type `\TYPO3\CMS\Extbase\Persistence\ObjectStorage`) where the posts are stored, e.g. in `function addPost(Post $post)` .
```suggestion
```

2021-05-14 13:24 UTC, franzholz commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +* `<f:link.action action="index" controller="Post" arguments="{blog : blog}">{blog.title} ({f:translate(key: 'blog.numberOfPosts', arguments: '{numberOfPosts: \'{blog.posts -> f:count()}\'}')})</f:li
All those parts are necessary for the following explanations.

2021-05-14 13:25 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +* `<f:link.action action="index" controller="Post" arguments="{blog : blog}">{blog.title} ({f:translate(key: 'blog.numberOfPosts', arguments: '{numberOfPosts: \'{blog.posts -> f:count()}\'}')})</f:li
I know, that's why I've split this into 2 bullets.

2021-05-25 20:03 UTC, linawolf approved these changes

2021-05-26 06:51 UTC, mbrodala requested changes

2021-05-26 06:51 UTC, mbrodala commented on Documentation/3-BlogExample/9-Rendering-the-output-with-fluid.rst
> +   file:`Resources/Private/Language/locallang.xml`. The number of `{blog.posts}` is counted using the
```suggestion
   file:`Resources/Private/Language/locallang.xlf`. The number of `{blog.posts}` is counted using the 
```

2021-05-26 06:51 UTC, mbrodala approved these changes

2021-05-26 06:51 UTC, merged