[DEPRECATION]  #94619 - Extbase ObjectManager
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #469
Opened 2021-07-30 14:55 UTC by linawolf

refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

2021-08-05 09:29 UTC, susannemoog commented
We should remove all other usages and references to the object manager with this commit, too, otherwise I fear it will be forgotten as we consider the deprecation "done".

2021-08-05 09:29 UTC, susannemoog requested changes
see comment above

2021-08-29 16:38 UTC, linawolf commented
I replaced the other usages.

2021-08-30 05:26 UTC, susannemoog approved these changes

2021-08-30 05:27 UTC, merged