Important: #95647 - Composer installations and extension usage
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #484
Opened 2021-11-03 21:21 UTC by linawolf

https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/11.4/Important-95647-ComposerInstallationsAndExtensionUsage.html
refs https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/issues/1449

releases: master, 11.5

2021-11-04 06:17 UTC, mbrodala requested changes

2021-11-04 06:17 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +legacy non-Composer installations. It is recommended to keep this files in
```suggestion
Legacy installations. It is recommended to keep this file in
```

2021-11-04 06:17 UTC, mbrodala commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +he file is located in the extension's
```suggestion
The file is located in the extension
```

2021-11-04 06:17 UTC, mbrodala commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
```suggestion
   Legacy installations.
```

2021-11-04 07:15 UTC, DavidBruchmann commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
I think the expression "legacy" might not be clear to everyone.

2021-11-04 07:18 UTC, DavidBruchmann commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
in the top it's used "legacy non-Composer" but it's not clear that bot expressions mean actually the same

2021-11-04 07:18 UTC, mbrodala commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
See the recent discussion in the docs Slack channel. This is what has been agreed upon as new name for the _Classic Mode_.

And yes, we should add links to these two at the top:

- https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/Installation/Install.html
- https://docs.typo3.org/m/typo3/tutorial-getting-started/master/en-us/Installation/LegacyInstallation.html

2021-11-04 07:52 UTC, DavidBruchmann commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
I see. My complaint is not about the expression itself but that it's not clear for the reader perhaps.
One sentence like "Installations without composer are called legacy installations" or 
```
Installation without composer = legacy installation
```
would show it as a direct assignment.
About the location of the explanation I don't mind so much but it wouldn't be too bad having it in top of this page even if it's explained on the pages again where you posted the links. (New) users understanding a page without reading much more are the most satisfied ones I guess.

2021-11-06 08:14 UTC, linawolf commented on Documentation/4-FirstExtension/2-create-folder-structure-and-configuration-files.rst
> +he file is located in the extension's
Keep reading: it is the extension's top level folder. So therefore the 's. Fixed the other one

2021-11-06 08:22 UTC, linawolf commented on Documentation/a-CodingGuidelines/Index.rst
> +   legacy non-Composer based installations.
On this page the word is used exactly once. I linked it to the getting started guide

2021-11-17 10:14 UTC, tomwarwick approved these changes

2021-11-17 10:14 UTC, susannemoog approved these changes

2021-11-17 10:15 UTC, merged