[TASK] Update hints of Extension Builder
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #503
Opened 2022-01-09 18:02 UTC by alexander-nitsche

See TYPO3-Documentation/T3DocTeam#174 for details.

2022-01-11 10:15 UTC, susannemoog requested changes

2022-01-11 10:15 UTC, susannemoog commented on Documentation/1-Installation/Index.rst
> +based TYPO3 extensions by providing you a GUI.
providing you a GUI sounds wrong.

2022-01-11 10:15 UTC, susannemoog commented on Documentation/1-Installation/Index.rst
> +But note that you should still familiarize yourself with the generated files
A sentence starting with 'But' sounds like a fragment.

2022-01-11 10:28 UTC, alexander-nitsche commented on Documentation/1-Installation/Index.rst
> +based TYPO3 extensions by providing you a GUI.
No problem. Adjust it to your liking so it sounds right to you. I will take care of the backport.

2022-01-11 10:28 UTC, alexander-nitsche commented on Documentation/1-Installation/Index.rst
> +But note that you should still familiarize yourself with the generated files
No problem. Adjust it to your liking so it sounds right to you. I will take care of the backport.

2022-01-11 14:11 UTC, alexander-nitsche commented on Documentation/1-Installation/Index.rst
> +based TYPO3 extensions by providing you a GUI.
Adjusted by Tom.

2022-01-11 14:11 UTC, alexander-nitsche commented on Documentation/1-Installation/Index.rst
> +But note that you should still familiarize yourself with the generated files
Adjusted by Tom.

2022-01-12 10:13 UTC, susannemoog approved these changes

2022-01-18 10:30 UTC, merged