Remove return statement when a redirect is used
TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid pull request #511
Opened 2022-02-22 16:28 UTC by AKaravas

Since redirects do not return anything, the documentation here has to be edited and return void instead.

2022-02-22 16:33 UTC, mbrodala requested changes

2022-02-22 16:33 UTC, mbrodala commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +   public function createAction(Organization $organization, Offer $newOffer) : void
```suggestion
   public function createAction(Organization $organization, Offer $newOffer): void
```

2022-02-22 16:33 UTC, mbrodala commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +      $this->redirect('show', 'Organization', NULL, ['organization' => $organization]);
Maybe also add a [note](https://docs.typo3.org/m/typo3/docs-how-to-document/main/en-us/WritingReST/Admonitions.html) somewhere close here to mention the fact that this method does not return a response.

This was changed in TYPO3v12:

- https://review.typo3.org/c/Packages/TYPO3.CMS/+/72497
- https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html

2022-02-23 09:45 UTC, linawolf commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +      $this->redirect('show', 'Organization', NULL, ['organization' => $organization]);
@mbrodala can it be merged like that or would you like to change the note?

2022-02-23 09:47 UTC, mbrodala commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +      $this->redirect('show', 'Organization', NULL, ['organization' => $organization]);
I'd move the note after the example and add more details about this, e.g. that this is deprecated in v11 and changed in v12.

2022-02-23 10:01 UTC, AKaravas commented
@mbrodala i added the suggestions. I moved the note after the example and added the deprecation notice

2022-02-23 10:09 UTC, mbrodala commented on Documentation/7-Controllers/1-Creating-Controllers-and-Actions.rst
> +   Redirects do not return anything, that is the reason why the above action returns void. This is going to be change in TYPO3 12 and it has been marked as deprecated. `Breaking: #96107 - Deprecated
```suggestion
   The redirect methods do not return any response, any method using them should return `void` accordingly. This has been `deprecated in TYPO3v11 <https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/Changelog/11.0/Deprecation-92784-ExtbaseControllerActionsMustReturnResponseInterface.html>`__ and was `dropped in TYPO3v12 where every action must return a response now <https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/12.0/Breaking-96107-DeprecatedFunctionalityRemoved.html>`__.
```

2022-02-23 13:29 UTC, mbrodala approved these changes

2022-02-23 13:29 UTC, merged

2022-02-23 13:29 UTC, mbrodala commented
Thanks a lot!